---
## Default Logstash configuration from logstash-docker.
## from https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash.yml
#
http.host: "0.0.0.0"

## for use pipelines.yml comment out path.config
# path.config: /usr/share/logstash/pipeline

## Disable X-Pack
## see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
##     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
#
#xpack.monitoring.enabled: false
#xpack.monitoring.elasticsearch.url: "http://10.140.0.14:9200"



##  The number of workers that will, in parallel, execute the filter and output stages of the pipeline. 
##  If you find that events are backing up, or that the CPU is not saturated, 
##  consider increasing this number to better utilize machine processing power.
pipeline.workers: 3

## https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html
queue.type: persisted
queue.max_bytes: 4gb
queue.max_events: 0
